
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 42;
  public static final int ASSIGNMENT = 9;
  public static final int ELSIF = 21;
  public static final int CASE = 17;
  public static final int EACH = 38;
  public static final int INTEGER = 24;
  public static final int INT = 32;
  public static final int INIT = 39;
  public static final int PAYBACK = 37;
  public static final int SCAN = 26;
  public static final int RCBRACKET = 7;
  public static final int SOUT = 27;
  public static final int OPSUMA = 13;
  public static final int SEMICOLON = 10;
  public static final int RPAR = 3;
  public static final int OPRES = 15;
  public static final int BOOL = 11;
  public static final int OPREL = 12;
  public static final int LOOP = 20;
  public static final int IF = 18;
  public static final int ID = 40;
  public static final int FAKER = 34;
  public static final int EOF = 0;
  public static final int RSBRACKET = 5;
  public static final int error = 1;
  public static final int PIPE = 25;
  public static final int BREAK = 29;
  public static final int VECTOR = 16;
  public static final int SWITCH = 31;
  public static final int LETTERS = 41;
  public static final int COLON = 8;
  public static final int DEFALT = 36;
  public static final int ELSE = 22;
  public static final int LCBRACKET = 6;
  public static final int FUNC = 23;
  public static final int WHILE = 19;
  public static final int SOUTLN = 28;
  public static final int DEFAULT = 30;
  public static final int LPAR = 2;
  public static final int DEF = 33;
  public static final int NOTHING = 35;
  public static final int OPMULT = 14;
  public static final int LSBRACKET = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "RPAR",
  "LSBRACKET",
  "RSBRACKET",
  "LCBRACKET",
  "RCBRACKET",
  "COLON",
  "ASSIGNMENT",
  "SEMICOLON",
  "BOOL",
  "OPREL",
  "OPSUMA",
  "OPMULT",
  "OPRES",
  "VECTOR",
  "CASE",
  "IF",
  "WHILE",
  "LOOP",
  "ELSIF",
  "ELSE",
  "FUNC",
  "INTEGER",
  "PIPE",
  "SCAN",
  "SOUT",
  "SOUTLN",
  "BREAK",
  "DEFAULT",
  "SWITCH",
  "INT",
  "DEF",
  "FAKER",
  "NOTHING",
  "DEFALT",
  "PAYBACK",
  "EACH",
  "INIT",
  "ID",
  "LETTERS",
  "CHAR"
  };
}

