
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 43;
  public static final int ASSIGNMENT = 14;
  public static final int ELSIF = 26;
  public static final int CASE = 22;
  public static final int EACH = 40;
  public static final int INTEGER = 4;
  public static final int INT = 36;
  public static final int INIT = 41;
  public static final int PAYBACK = 39;
  public static final int SCAN = 30;
  public static final int RCBRACKET = 12;
  public static final int NOT = 42;
  public static final int SOUT = 31;
  public static final int SEMICOLON = 15;
  public static final int OPSUMA = 18;
  public static final int RPAR = 8;
  public static final int OPRES = 20;
  public static final int BOOL = 2;
  public static final int COMMA = 16;
  public static final int OPREL = 17;
  public static final int LOOP = 25;
  public static final int IF = 23;
  public static final int FAKER = 38;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int RSBRACKET = 10;
  public static final int error = 1;
  public static final int PIPE = 29;
  public static final int BREAK = 33;
  public static final int VECTOR = 21;
  public static final int SWITCH = 35;
  public static final int LETTERS = 3;
  public static final int COLON = 13;
  public static final int ELSE = 27;
  public static final int LCBRACKET = 11;
  public static final int FUNC = 28;
  public static final int WHILE = 24;
  public static final int SOUTLN = 32;
  public static final int DEFAULT = 34;
  public static final int LPAR = 7;
  public static final int DEF = 37;
  public static final int NOTHING = 5;
  public static final int OPMULT = 19;
  public static final int LSBRACKET = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "LETTERS",
  "INTEGER",
  "NOTHING",
  "ID",
  "LPAR",
  "RPAR",
  "LSBRACKET",
  "RSBRACKET",
  "LCBRACKET",
  "RCBRACKET",
  "COLON",
  "ASSIGNMENT",
  "SEMICOLON",
  "COMMA",
  "OPREL",
  "OPSUMA",
  "OPMULT",
  "OPRES",
  "VECTOR",
  "CASE",
  "IF",
  "WHILE",
  "LOOP",
  "ELSIF",
  "ELSE",
  "FUNC",
  "PIPE",
  "SCAN",
  "SOUT",
  "SOUTLN",
  "BREAK",
  "DEFAULT",
  "SWITCH",
  "INT",
  "DEF",
  "FAKER",
  "PAYBACK",
  "EACH",
  "INIT",
  "NOT",
  "CHAR"
  };
}

